theme: minima
title: "Research Journey"
description: "My personal website showcasing my research and projects."
author: "Robin Bretin"


# Navigation links
header_pages:
  - about.md
  - research.md
  - publication.md
  - contact.md

