theme: minima
title: "Robin Research Journey"
description: "A personal website showcasing my research and projects."


# Navigation links
header_pages:
  - about.md
  - research.md
  - publication.md
  - contact.md