theme: minima
title: "Robin Research Journey"
description: "A personal website showcasing my research and projects."


# Navigation links
header_pages:
  - index.md
  - about.md
  - research.md
  - publications.md
  - contact.md


gems:
  - jekyll-scholar


scholar:
  source: "assets/MyPublications.bib" # Path to your BibTeX file
  style: "apa" # Or another style like "ieee", "mla"
  bibliography: "MyPublications.bib"